#!/usr/bin/env bash
set -eu -o pipefail

if [ -n "${SSH_TUNNEL_USER}" ]; then
  set +x
  source ./bosh-windows-stemcell-builder-ci/ci/common-scripts/setup_bosh_proxy.sh
  setup_bosh_proxy "${SSH_TUNNEL_USER}" "${SSH_TUNNEL_IP}" "${SSH_TUNNEL_PRIVATE_KEY}"
fi

set -x

# shellcheck disable=SC2086
resolved_stemcell_path=$(readlink -f ${STEMCELL_PATH})
json_safe_bosh_ca_cert="${BOSH_CA_CERT//$'\n'/\\n}"

pushd stemcell-builder/acceptance_test
  export CONFIG_JSON=config.json

  cat > "${CONFIG_JSON}" <<-END_OF_CONFIG
  {
    "bosh": {
      "ca_cert": "${json_safe_bosh_ca_cert}",
      "client": "${BOSH_CLIENT}",
      "client_secret": "${BOSH_CLIENT_SECRET}",
      "target": "${BOSH_ENVIRONMENT}"
    },
    "stemcell_path": "${resolved_stemcell_path}",
    "stemcell_os": "${STEMCELL_OS}",
    "az": "${AZ}",
    "vm_type": "${VM_TYPE}",
    "root_ephemeral_vm_type": "${ROOT_EPHEMERAL_VM_TYPE}",
    "vm_extensions": "${VM_EXTENSIONS}",
    "network": "${NETWORK}",
    "default_username": "${DEFAULT_USERNAME}",
    "default_password": "${DEFAULT_PASSWORD}"
  }
END_OF_CONFIG

  go run github.com/onsi/ginkgo/v2/ginkgo run -r -v \
    --timeout="${GINKGO_TIMEOUT}" \
    --focus="${GINKGO_FOCUS}" \
    --skip="${GINKGO_SKIP}" .
popd
