---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stemcell-builder
  - name: stemcell

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/run-bwats/run

params:
  ACCOUNT_JSON:
  AZ: z1
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  GINKGO_FOCUS:
  GINKGO_SKIP:
  GINKGO_TIMEOUT: 2h # Ginkgo v2 default is 1h
  IAAS:
  NETWORK: default
  SSH_TUNNEL_IP:
  SSH_TUNNEL_PRIVATE_KEY:
  SSH_TUNNEL_USER:
  STEMCELL_OS:
  STEMCELL_PATH: stemcell/*.tgz
  VM_EXTENSIONS: ""
  VM_TYPE: large
  ROOT_EPHEMERAL_VM_TYPE:
  BOSH_GW_USER:
  BWATS_BOSH_TIMEOUT:
  DEFAULT_USERNAME:
  DEFAULT_PASSWORD:
