#!/usr/bin/env bash
set -eu -o pipefail
set -x

if [ -n "${AWS_ROLE_ARN}" ]; then
  aws configure --profile creds_account set aws_access_key_id "${PACKER_AWS_ACCESS_KEY}"
  set +x
  aws configure --profile creds_account set aws_secret_access_key "${PACKER_AWS_SECRET_KEY}"
  set -x
  aws configure --profile resource_account set source_profile "creds_account"
  aws configure --profile resource_account set role_arn "${AWS_ROLE_ARN}"
  aws configure --profile resource_account set region "${AWS_REGION}"
  unset AWS_REGION
  export AWS_PROFILE=resource_account
else
  export AWS_ACCESS_KEY="${PACKER_AWS_ACCESS_KEY}"
  set +x
  export AWS_SECRET_KEY="${PACKER_AWS_SECRET_KEY}"
  set -x
fi

pushd lgpo-binary
  unzip LGPO.zip
popd

CONCOURSE_ROOT="$(pwd)"

"${CONCOURSE_ROOT}/bosh-windows-stemcell-builder-ci/ci/tasks/build-agent-zip/run.sh"
"${CONCOURSE_ROOT}/bosh-windows-stemcell-builder-ci/ci/tasks/build-psmodules-zip/run.sh"

pushd stemcell-builder
  bundle install --without test

  rake build:aws

  mv bosh-windows-stemcell/* ../bosh-windows-stemcell

  mv hotfixes.log ../hotfix-log/
popd
