#!/usr/bin/env bash
set -eu -o pipefail
set -x

CONCOURSE_ROOT="$(pwd)"

if [ -n "${AWS_ROLE_ARN}" ]; then
  aws configure --profile creds_account set aws_access_key_id "${PACKER_AWS_ACCESS_KEY}"
  set +x
  aws configure --profile creds_account set aws_secret_access_key "${PACKER_AWS_SECRET_KEY}"
  set -x
  aws configure --profile resource_account set source_profile "creds_account"
  aws configure --profile resource_account set role_arn "${AWS_ROLE_ARN}"
  aws configure --profile resource_account set region "${AWS_REGION}"
  unset AWS_REGION
  export AWS_PROFILE=resource_account
else
  export AWS_ACCESS_KEY="${PACKER_AWS_ACCESS_KEY}"
  set +x
  export AWS_SECRET_KEY="${PACKER_AWS_SECRET_KEY}"
  set -x
fi
export PACKER_CI_PRIVATE_KEY_LOCATION="${CONCOURSE_ROOT}/packer-ci-private-key/packer_key"
mkdir -p "$(dirname "${PACKER_CI_PRIVATE_KEY_LOCATION}")"
echo "${PACKER_CI_PRIVATE_KEY}" > "${PACKER_CI_PRIVATE_KEY_LOCATION}"
chmod 600 "${PACKER_CI_PRIVATE_KEY_LOCATION}"

pushd lgpo-binary
  unzip LGPO.zip
popd

pushd stemcell-builder
  mkdir -p build
  cp "${CONCOURSE_ROOT}/psmodules-zip-output/bosh-psmodules.zip" "${CONCOURSE_ROOT}/bosh-agent/agent.zip" build

  bundle install
  bundle exec rake build:aws

  mv bosh-windows-stemcell/* ../bosh-windows-stemcell

  mv hotfixes.log ../hotfix-log/
popd
