---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: submission-id

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/partner-center-go-live/run

params:
  PARTNER_PORTAL_TENANT_ID:
  PARTNER_PORTAL_CLIENT_ID:
  PARTNER_PORTAL_CLIENT_SECRET:
  AZURE_OFFER:
