// Code generated by counterfeiter. DO NOT EDIT.
package remotemanagerfakes

import (
	"sync"
	"time"

	"github.com/cloudfoundry/bosh-windows-stemcell-builder/stembuild/remotemanager"
)

type FakeWinRMClientFactoryI struct {
	BuildStub        func(time.Duration) (remotemanager.WinRMClient, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 time.Duration
	}
	buildReturns struct {
		result1 remotemanager.WinRMClient
		result2 error
	}
	buildReturnsOnCall map[int]struct {
		result1 remotemanager.WinRMClient
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWinRMClientFactoryI) Build(arg1 time.Duration) (remotemanager.WinRMClient, error) {
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 time.Duration
	}{arg1})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWinRMClientFactoryI) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeWinRMClientFactoryI) BuildCalls(stub func(time.Duration) (remotemanager.WinRMClient, error)) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *FakeWinRMClientFactoryI) BuildArgsForCall(i int) time.Duration {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWinRMClientFactoryI) BuildReturns(result1 remotemanager.WinRMClient, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 remotemanager.WinRMClient
		result2 error
	}{result1, result2}
}

func (fake *FakeWinRMClientFactoryI) BuildReturnsOnCall(i int, result1 remotemanager.WinRMClient, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 remotemanager.WinRMClient
			result2 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 remotemanager.WinRMClient
		result2 error
	}{result1, result2}
}

func (fake *FakeWinRMClientFactoryI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWinRMClientFactoryI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ remotemanager.WinRMClientFactoryI = new(FakeWinRMClientFactoryI)
