#!/usr/bin/env bash

set -eu -o pipefail
set -x

cd stemcell-builder/acceptance_test

go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run ./...

go test -c

go run github.com/onsi/ginkgo/v2/ginkgo run --dry-run -v
