#!/usr/bin/env ruby

puts <<-HEREDOC
\e[91m
╔╦╗┌─┐┌─┐┬┌─╔═╗┬  ┬┌─┐╔╦╗┌─┐┌─┐┬
║║║│ ││  ├┴┐║ ║└┐┌┘├┤  ║ │ ││ ││
╩ ╩└─┘└─┘┴ ┴╚═╝ └┘ └   ╩ └─┘└─┘┴─┘
this is not the real ovf tool
\e[0m
HEREDOC


require 'fileutils'

OUTPUT_DIR = ARGV[1]
FileUtils.cp(File.join(__dir__, "image"), OUTPUT_DIR)
