#!/usr/bin/env ruby

require 'fileutils'
require 'json'

packer_config = ARGV.last
content = File.read(packer_config)
output_directory = JSON.parse(content)['builders'][0]['output_directory']
FileUtils.mkdir_p(output_directory)
update_list_provisioner = JSON.parse(content)['provisioners']
  .detect{|p| p['type'] == 'file' && p['direction'] == 'download'}
if update_list_provisioner
  update_list_path = update_list_provisioner['destination']
  FileUtils.mkdir_p(File.dirname(update_list_path))
  File.write(update_list_path, "some-updates")
end
Dir.chdir(output_directory) do
  File.write("file.vmx", "banana")
end
