#!/usr/bin/env ruby
require 'fileutils'

puts <<-HEREDOC
\e[91m
╔╦╗┌─┐┌─┐┬┌─╔═╗┌┬┐┌─┐┌┬┐╔╗ ┬ ┬┬┬  ┌┬┐
║║║│ ││  ├┴┐╚═╗ │ ├┤ │││╠╩╗│ │││   ││
╩ ╩└─┘└─┘┴ ┴╚═╝ ┴ └─┘┴ ┴╚═╝└─┘┴┴─┘─┴┘
This is not the real stembuild
\e[0m
HEREDOC

    output_dir =
  if ARGV[0] == "package" # stembuild used to package packer output vmdk into tgz
    ARGV[6]
  end

FileUtils.cp(File.join(__dir__, "bosh-stemcell-5555.5-vsphere-esxi-windows2012R2-go_agent.tgz"), output_dir)
File.write(File.join(output_dir, "myargs"), ARGV.inspect)
