// Code generated by counterfeiter. DO NOT EDIT.
package commandparserfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-windows-stemcell-builder/stembuild/commandparser"
)

type FakeConstructMessenger struct {
	ArgumentsNotProvidedStub        func()
	argumentsNotProvidedMutex       sync.RWMutex
	argumentsNotProvidedArgsForCall []struct {
	}
	CannotConnectToVMStub        func(error)
	cannotConnectToVMMutex       sync.RWMutex
	cannotConnectToVMArgsForCall []struct {
		arg1 error
	}
	CannotPrepareVMStub        func(error)
	cannotPrepareVMMutex       sync.RWMutex
	cannotPrepareVMArgsForCall []struct {
		arg1 error
	}
	LGPONotFoundStub        func()
	lGPONotFoundMutex       sync.RWMutex
	lGPONotFoundArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConstructMessenger) ArgumentsNotProvided() {
	fake.argumentsNotProvidedMutex.Lock()
	fake.argumentsNotProvidedArgsForCall = append(fake.argumentsNotProvidedArgsForCall, struct {
	}{})
	stub := fake.ArgumentsNotProvidedStub
	fake.recordInvocation("ArgumentsNotProvided", []interface{}{})
	fake.argumentsNotProvidedMutex.Unlock()
	if stub != nil {
		fake.ArgumentsNotProvidedStub()
	}
}

func (fake *FakeConstructMessenger) ArgumentsNotProvidedCallCount() int {
	fake.argumentsNotProvidedMutex.RLock()
	defer fake.argumentsNotProvidedMutex.RUnlock()
	return len(fake.argumentsNotProvidedArgsForCall)
}

func (fake *FakeConstructMessenger) ArgumentsNotProvidedCalls(stub func()) {
	fake.argumentsNotProvidedMutex.Lock()
	defer fake.argumentsNotProvidedMutex.Unlock()
	fake.ArgumentsNotProvidedStub = stub
}

func (fake *FakeConstructMessenger) CannotConnectToVM(arg1 error) {
	fake.cannotConnectToVMMutex.Lock()
	fake.cannotConnectToVMArgsForCall = append(fake.cannotConnectToVMArgsForCall, struct {
		arg1 error
	}{arg1})
	stub := fake.CannotConnectToVMStub
	fake.recordInvocation("CannotConnectToVM", []interface{}{arg1})
	fake.cannotConnectToVMMutex.Unlock()
	if stub != nil {
		fake.CannotConnectToVMStub(arg1)
	}
}

func (fake *FakeConstructMessenger) CannotConnectToVMCallCount() int {
	fake.cannotConnectToVMMutex.RLock()
	defer fake.cannotConnectToVMMutex.RUnlock()
	return len(fake.cannotConnectToVMArgsForCall)
}

func (fake *FakeConstructMessenger) CannotConnectToVMCalls(stub func(error)) {
	fake.cannotConnectToVMMutex.Lock()
	defer fake.cannotConnectToVMMutex.Unlock()
	fake.CannotConnectToVMStub = stub
}

func (fake *FakeConstructMessenger) CannotConnectToVMArgsForCall(i int) error {
	fake.cannotConnectToVMMutex.RLock()
	defer fake.cannotConnectToVMMutex.RUnlock()
	argsForCall := fake.cannotConnectToVMArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConstructMessenger) CannotPrepareVM(arg1 error) {
	fake.cannotPrepareVMMutex.Lock()
	fake.cannotPrepareVMArgsForCall = append(fake.cannotPrepareVMArgsForCall, struct {
		arg1 error
	}{arg1})
	stub := fake.CannotPrepareVMStub
	fake.recordInvocation("CannotPrepareVM", []interface{}{arg1})
	fake.cannotPrepareVMMutex.Unlock()
	if stub != nil {
		fake.CannotPrepareVMStub(arg1)
	}
}

func (fake *FakeConstructMessenger) CannotPrepareVMCallCount() int {
	fake.cannotPrepareVMMutex.RLock()
	defer fake.cannotPrepareVMMutex.RUnlock()
	return len(fake.cannotPrepareVMArgsForCall)
}

func (fake *FakeConstructMessenger) CannotPrepareVMCalls(stub func(error)) {
	fake.cannotPrepareVMMutex.Lock()
	defer fake.cannotPrepareVMMutex.Unlock()
	fake.CannotPrepareVMStub = stub
}

func (fake *FakeConstructMessenger) CannotPrepareVMArgsForCall(i int) error {
	fake.cannotPrepareVMMutex.RLock()
	defer fake.cannotPrepareVMMutex.RUnlock()
	argsForCall := fake.cannotPrepareVMArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConstructMessenger) LGPONotFound() {
	fake.lGPONotFoundMutex.Lock()
	fake.lGPONotFoundArgsForCall = append(fake.lGPONotFoundArgsForCall, struct {
	}{})
	stub := fake.LGPONotFoundStub
	fake.recordInvocation("LGPONotFound", []interface{}{})
	fake.lGPONotFoundMutex.Unlock()
	if stub != nil {
		fake.LGPONotFoundStub()
	}
}

func (fake *FakeConstructMessenger) LGPONotFoundCallCount() int {
	fake.lGPONotFoundMutex.RLock()
	defer fake.lGPONotFoundMutex.RUnlock()
	return len(fake.lGPONotFoundArgsForCall)
}

func (fake *FakeConstructMessenger) LGPONotFoundCalls(stub func()) {
	fake.lGPONotFoundMutex.Lock()
	defer fake.lGPONotFoundMutex.Unlock()
	fake.LGPONotFoundStub = stub
}

func (fake *FakeConstructMessenger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.argumentsNotProvidedMutex.RLock()
	defer fake.argumentsNotProvidedMutex.RUnlock()
	fake.cannotConnectToVMMutex.RLock()
	defer fake.cannotConnectToVMMutex.RUnlock()
	fake.cannotPrepareVMMutex.RLock()
	defer fake.cannotPrepareVMMutex.RUnlock()
	fake.lGPONotFoundMutex.RLock()
	defer fake.lGPONotFoundMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConstructMessenger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commandparser.ConstructMessenger = new(FakeConstructMessenger)
