#!/usr/bin/env bash
set -eu -o pipefail
set -x

pushd lgpo-binary
  unzip LGPO.zip
popd

CONCOURSE_ROOT="$(pwd)"

pushd stemcell-builder
  mkdir -p build
  cp "${CONCOURSE_ROOT}/psmodules-zip-output/bosh-psmodules.zip" "${CONCOURSE_ROOT}/bosh-agent/agent.zip" build

  bundle install --without test
  rake build:gcp

  mv bosh-windows-stemcell/* ../bosh-windows-stemcell

  mv hotfixes.log ../hotfix-log/
popd
