---
platform: windows
inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stemcell-builder
  - name: pester

run:
  path: powershell
  args:
    - "-Command"
    - "& {
            Import-Module ./bosh-windows-stemcell-builder-ci/ci/common-scripts/setup-windows-container.psm1;
            Set-TmpDir;
            Import-Module ./Pester/pester.psm1;
            pushd stemcell-builder/stembuild/stemcell-automation;
            $result=Invoke-Pester -PassThru;
            popd;
            Write-Host \"Failed Tests:\"$result.FailedCount;
            exit $result.FailedCount
          }"