#!/usr/bin/env bash
set -eu -o pipefail
set -x

if [ -n "${AWS_ROLE_ARN}" ]; then
  aws configure --profile creds_account set aws_access_key_id "${AWS_ACCESS_KEY}"
  set +x
  aws configure --profile creds_account set aws_secret_access_key "${AWS_SECRET_KEY}"
  set -x
  aws configure --profile resource_account set source_profile "creds_account"
  aws configure --profile resource_account set role_arn "${AWS_ROLE_ARN}"
  unset AWS_ACCESS_KEY
  unset AWS_SECRET_KEY
  export AWS_PROFILE=resource_account
else
  aws configure set aws_access_key_id "${AWS_ACCESS_KEY}"
  set +x
  aws configure set aws_secret_access_key "${AWS_SECRET_KEY}"
  set -x
fi

CONCOURSE_ROOT="$(pwd)"

"${CONCOURSE_ROOT}/bosh-windows-stemcell-builder-ci/ci/tasks/build-agent-zip/run.sh"
"${CONCOURSE_ROOT}/bosh-windows-stemcell-builder-ci/ci/tasks/build-psmodules-zip/run.sh"

pushd stemcell-builder
  bundle install --without test

  rake build:aws_ami

  mv copied-regional-stemcells/*.tgz ../copied-regional-stemcells
popd
