---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stemcell-builder
  - name: version
  - name: amis
  - name: default-stemcell

outputs:
  - name: copied-regional-stemcells

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/copy-aws-stemcell/run

params:
  OS_VERSION:
  AWS_ACCESS_KEY:
  AWS_ROLE_ARN:
  AWS_SECRET_KEY:
  REGIONS:
  VERSION_DIR: ../version
  AMIS_DIR: ../amis
  DEFAULT_STEMCELL_DIR: ../default-stemcell
