#!/bin/bash

set -e -x

export GOPATH="$PWD"
export PATH="$PATH:$GOPATH/bin"
export UPDATES_LIST=$PWD/updates-list

go get -u -t "github.com/onsi/ginkgo/..."
go get -u -t "github.com/onsi/gomega/..."
ginkgo -r -v "$GOPATH/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests"

pushd updates-list
  tempDir=$(mktemp -d)
  tar -xzf *.tgz -C $tempDir
  cp $tempDir/errand/*.csv .
popd
