---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: vhd-uri

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/partner-center-submit-preview/run

params:
  PARTNER_PORTAL_TENANT_ID:
  PARTNER_PORTAL_CLIENT_ID:
  PARTNER_PORTAL_CLIENT_SECRET:
  AZURE_OFFER:
  AZURE_SKU:
  IMAGE_VERSION:
  AZURE_PUBLISHED_STORAGE_ACCOUNT:
  AZURE_PUBLISHED_STORAGE_ACCESS_KEY:
  AZURE_CONTAINER_NAME:
