---
platform: linux

inputs:
- name: bosh-windows-stemcell-builder-ci
- name: stemcell-builder

outputs:
- name: psmodules-zip-output

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/build-psmodules-zip/run.sh

params:
  ZIP_OUTPUT_DIR: psmodules-zip-output
