#!/usr/bin/env bash
set -eu -o pipefail
set -x

pushd stemcell-builder
  bundle install
  bundle exec rake build:aws_aggregate

  mv bosh-windows-stemcell/*.tgz ../bosh-windows-stemcell
  mv bosh-windows-stemcell/*.sha ../sha
popd