#!/usr/bin/env bash
set -eu -o pipefail
set -x

pushd stemcell-builder
  bundle install
  bundle exec rake publish:gcp
  bundle exec rake gcp:label:for_test
popd

mv bosh-windows-stemcell/*.tgz untested-stemcell
