---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: gcp-tested
  - name: version

outputs:
  - name: final-stemcell

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/publish-gcp-stemcell/run

params:
  ACCOUNT_JSON:
