---
platform: linux

inputs:
- name: bosh-windows-stemcell-builder-ci

outputs:
- name: azstemcell-binary-out

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/build-azstemcell/run.sh

params:
  GITHUB_ACCESS_TOKEN:
