// Code generated by counterfeiter. DO NOT EDIT.
package filesystemfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-windows-stemcell-builder/stembuild/filesystem"
)

type FakeFileSystem struct {
	GetAvailableDiskSpaceStub        func(string) (uint64, error)
	getAvailableDiskSpaceMutex       sync.RWMutex
	getAvailableDiskSpaceArgsForCall []struct {
		arg1 string
	}
	getAvailableDiskSpaceReturns struct {
		result1 uint64
		result2 error
	}
	getAvailableDiskSpaceReturnsOnCall map[int]struct {
		result1 uint64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFileSystem) GetAvailableDiskSpace(arg1 string) (uint64, error) {
	fake.getAvailableDiskSpaceMutex.Lock()
	ret, specificReturn := fake.getAvailableDiskSpaceReturnsOnCall[len(fake.getAvailableDiskSpaceArgsForCall)]
	fake.getAvailableDiskSpaceArgsForCall = append(fake.getAvailableDiskSpaceArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetAvailableDiskSpaceStub
	fakeReturns := fake.getAvailableDiskSpaceReturns
	fake.recordInvocation("GetAvailableDiskSpace", []interface{}{arg1})
	fake.getAvailableDiskSpaceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFileSystem) GetAvailableDiskSpaceCallCount() int {
	fake.getAvailableDiskSpaceMutex.RLock()
	defer fake.getAvailableDiskSpaceMutex.RUnlock()
	return len(fake.getAvailableDiskSpaceArgsForCall)
}

func (fake *FakeFileSystem) GetAvailableDiskSpaceCalls(stub func(string) (uint64, error)) {
	fake.getAvailableDiskSpaceMutex.Lock()
	defer fake.getAvailableDiskSpaceMutex.Unlock()
	fake.GetAvailableDiskSpaceStub = stub
}

func (fake *FakeFileSystem) GetAvailableDiskSpaceArgsForCall(i int) string {
	fake.getAvailableDiskSpaceMutex.RLock()
	defer fake.getAvailableDiskSpaceMutex.RUnlock()
	argsForCall := fake.getAvailableDiskSpaceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFileSystem) GetAvailableDiskSpaceReturns(result1 uint64, result2 error) {
	fake.getAvailableDiskSpaceMutex.Lock()
	defer fake.getAvailableDiskSpaceMutex.Unlock()
	fake.GetAvailableDiskSpaceStub = nil
	fake.getAvailableDiskSpaceReturns = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakeFileSystem) GetAvailableDiskSpaceReturnsOnCall(i int, result1 uint64, result2 error) {
	fake.getAvailableDiskSpaceMutex.Lock()
	defer fake.getAvailableDiskSpaceMutex.Unlock()
	fake.GetAvailableDiskSpaceStub = nil
	if fake.getAvailableDiskSpaceReturnsOnCall == nil {
		fake.getAvailableDiskSpaceReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 error
		})
	}
	fake.getAvailableDiskSpaceReturnsOnCall[i] = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakeFileSystem) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFileSystem) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ filesystem.FileSystem = new(FakeFileSystem)
