#!/usr/bin/env bash
set -eu -o pipefail
set -x

LGPO_DOWNLOAD_URI="https://download.microsoft.com/download/8/5/C/85C25433-A1B0-4FFA-9429-7E023E7DA8D8/LGPO.zip"
LGPO_OUTPUT_FILE="LGPO.zip"

pushd lgpo-binary
  curl --location "${LGPO_DOWNLOAD_URI}" \
    --output "${LGPO_OUTPUT_FILE}"
popd
