#!/usr/bin/env ruby

require 'fileutils'
require 'json'

# Parse packer config to determine the updates list destination path
packer_config = ARGV.last
content = File.read(packer_config)
# update_list_path = JSON.parse(content)['provisioners']
#   .detect{|p| p['type'] == 'file' && p['direction'] == 'download'}['destination']

# FileUtils.mkdir_p(File.dirname(update_list_path))
# File.write(update_list_path, "some-updates")

puts "azure-arm,artifact,0\\nOSDiskUriReadOnlySas: https://storageaccount.blob.core.windows.net/system/Microsoft.Compute/Images/bosh-stemcell-osDisk.blah.vhd?se=2017-05-04T21%3A53%3A11Z&sig=mysig&sp=r&sr=b&sv=2015-02-21"
