---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: bosh/windows-stemcell-ci

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stemcell-builder
  - name: version
  - name: ovftool

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/test-units-stembuild-linux/run.sh
